export const CONTRACT_ID = 'CAZ3ZKHGEZYCHEMHSCR4GE4XPTUY4T6BAKLQNI2QKYS63FNNTOXNNYIV';
export const SOROBAN_RPC_URL = 'https://soroban-testnet.stellar.org';
export const NATIVE_TOKEN = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2EZ4YXL5';
