export const CONTRACT_ID = 'CCBUYWVTE4GA54M2NQU3NIHFNR3YBA6VV4GQADGEXGEMJVJZDJ7LRITV';
export const SOROBAN_RPC_URL = 'https://soroban-testnet.stellar.org';
export const NATIVE_TOKEN = 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
export const NETWORK = 'TESTNET';

